apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "cirros-px-pvc"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "http://download.cirros-cloud.net/0.3.0/cirros-0.3.0-x86_64-disk.img"
spec:
  storageClassName: px-csi-db
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
