apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pvc-block"
spec:
  volumeMode: Block
  storageClassName: px-csi-db
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
