apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: 2018-07-04T15:03:08Z
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: ubuntu-csi-vm 
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: ubuntu-csi-vm
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          interfaces:
            - name: default
              masquerade: {}
          disks:
          - disk:
              bus: virtio
            name: disk0
          - disk:
              bus: virtio
            name: disk1
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: ubuntu-px-csi-pvc
      - name: disk1 
        persistentVolumeClaim:
          claimName: pvc-block
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: ubuntu-vm
            password: test123
            chpasswd: { expire: False }
            ssh_pwauth: True
            disable_root: false
        name: cloudinitdisk
