apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-px-dv
spec:
  source:
      http:
         url: "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img"
  pvc:
    storageClassName: px-csi-db
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
