apiVersion: snapshot.kubevirt.io/v1alpha1
kind: VirtualMachineRestore
metadata:
  name: rs-1
spec:
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: ubuntu-vm-1
  virtualMachineSnapshotName: snap-testvm-block
